# Generated by Django 6.0 on 2026-01-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
