# Generated by Django 6.0 on 2026-01-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymenthistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user',
        ),
    ]
