# Generated by Django 6.0 on 2026-01-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_paymenthistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plan_expiry_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
