# Generated by Django 6.0 on 2026-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_profile_plan_remove_profile_plan_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professonal', 'Professional'), ('business', 'Business')], default='starter', max_length=20),
        ),
    ]
